host: 'ai-oryouri-naming.herokuapp.com'

sorcery:
  line_callback_url: 'https://www.ai-oryouri-naming.com/oauth/callback?provider=line'
  google_callback_url: 'https://www.ai-oryouri-naming.com/oauth/callback?provider=google'